<main>
    <form method="post" action="logic/register.php">
        <label for="first-name">Prénom : </label>
        <input type="text" name="first-name"/>
        <br>
        <label for="last-name">Nom : </label>
        <input type="text" name="last-name"/>
        <br>
        <label for="email">Adresse mail : </label>
        <input type="email" name="email"/>
        <br>
        <label for="password">Mot de passe : </label>
        <input type="password" name="password"/>
        <br>
        <button type="submit">Inscription</button>
    </form>
</main>